### PR TITLE
Payload Passthru Mode

### PR DESCRIPTION
**Pull request by KSDaemon**
This PR includes:

* New feature: Payload Passthru Mode (PPT Mode for short). PPT Mode is an evolution of `payload_transparency` feature and now is officially described in  [WAMP spec](https://wamp-proto.org/wamp_latest_ietf.html#name-payload-passthru-mode)
* Tests for PPT Mode
* Extended serializers with methods for item serialization (in addition to serialization of the whole wamp message)
* As new attributes were added to `options/details` parameter, some API method were modified (e.g. instead of passing just one positional boolean argument for `progress`, now options are done mostly everywhere across library in same manner: named arguments to be able to pass all desired options at once)
* Some parts were refactored
* Tests were refactored a bit
* Some preparations for End-2-end encryption (E2EE for short), that runs on top of ppt mode

There are definitely places to refactor and optimize but the main feature is working.

### CODE REVIEW

**Comment by konsultaner** [comment]
@KSDaemon Thanks for all the work :) I'm not a contribution pro, so one stupid question. Can I somehow edit your code? I would like to reorder some of it. I would also like to add some unit tests and rename some code parts.

**Comment by KSDaemon** [comment]
Hi, @konsultaner! Well, there are a few possible options for your question:
* As my changes are in my own fork, I can add you as a contributor so you can edit code there in place.
* Or you can add me as a contributor here, I'll propagate changes to a branch in this repo, so you'll be able to checkout and edit.

I'll be glad to become a real contributor here. It also helps btw in code review flows, issues labeling and etc.
But of course, it's up to you.

**Comment by KSDaemon** [comment]
@konsultaner Thnx! Well, it is not only your own code style but a community-wide ;) In any project with more than one developer all code should be developed and reviewed through the PRs! So let's work on this together!

**Comment by konsultaner** [comment]
@KSDaemon sorry, my first project with larger contributions from other developers 🙈

**Comment by KSDaemon** [comment]
@konsultaner Don't worry! No problem! I'm glad to help! Just msg me here, by email, or any messenger.

**Comment by konsultaner** [comment]
@KSDaemon do I need to start the new branch or can you do this now?

**Comment by KSDaemon** [comment]
Closing in favor of https://github.com/konsultaner/connectanum-dart/pull/53

**Comment by KSDaemon** [comment]
@konsultaner Thnx for inviting me!
See https://github.com/konsultaner/connectanum-dart/pull/53. Feel free to checkout to `ppt-mode` branch sync with master and update as needed.

**Pull request closed without merging**
