### PR TITLE
Missing codecov msgpack tests

### PR DESCRIPTION
**Pull request by liquidiert**
Probably not the worst idea to add the missing tests, as I was parsing the payload arguments wrong.

Further changes:
- test for deserializing Error
- test for deserializing Goodbye
- test for serializing Event
- added args for Event
- fixed bug that would swallow payload arguments

### CODE REVIEW

**Comment by konsultaner** [comment]
@liquidiert thank you!! very nice work.

**Comment by liquidiert** [comment]
@konsultaner no need! Thanks for beeing so active 😄

**Comment by konsultaner** [comment]
@liquidiert I also use this code in my own projects. That helps. ;)

**Comment by liquidiert** [comment]
Haha same reason I wanted it 😂👌

**Pull request merged**
