### PR TITLE
add test client for wamp cryptosign; fix pubkey in authextra

### PR DESCRIPTION
**Pull request by oberstet**

### CODE REVIEW

**Comment by konsultaner** [comment]
could you remove the `example/test_client_wampcs.dart`?

**Comment by oberstet** [comment]
sure. removed. so I think this should work now (wamp-cs) .. even though I would like to check the assigned session details

that is, 1) here https://github.com/oberstet/scratchbox/blob/51ec82a1f85a8fc3cbea3208fb2af70c1d08a4c4/flutter/ex1/test_client_wampcs.dart#L36

the other Q I am wondering: 3) ? it should be possible to provide call args?

Q 2): that is my problem now;) not related directly to WAMP-Cryptosign or WAMP in general ...

This could mean lots of "fun" .. Eth support in Dart ... no clue.

**Comment by konsultaner** [comment]
> 1)

https://github.com/konsultaner/connectanum-dart/blob/5928f1e8f913d6fba1647b95fc534e4070b71a56/lib/src/protocol/session.dart#L146

```dart
session1.authId
session1.roles
...
```

> 2)

Is this also a ed25519 key?

> 3)

```dart
final bool is_member = await session1.call(
     'xbr.network.is_member',
      arguments: [ethkey_adr],
      argumentsKeywords: {},
      options: CallOptions(),
      cancelCompleter: Completer() 
);
```

**Comment by oberstet** [comment]
^ 1. + 3.: thanks for your hints! got it.

rgd 2:

* no, Ethereum is using Koblitz elliptic curves, aka **secp256k1** (Ed25519 is using Curve25519, aka **ec25519**)
* further, we need support for EIP712

The first one seems available in https://github.com/simolus3/web3dart - I am digging into that now.

Rgd the latter: https://github.com/simolus3/web3dart/issues/134

**Pull request merged**
